[#p5,reftext=P.5]
=== (P.5) Required technology elements

ifdef::env-draft[]
TIP: _External systems, hardware and software, expected to be necessary for building the system. It lists external technology elements, such as program libraries and hardware devices, that the project is expected to require. Although the actual use of such products belongs to design and implementation rather than requirements, it is part of the requirements task to identify elements whose availability is critical to the success of the project — an important element of risk analysis (<<p6>>)._  <<BM22>>
endif::[]

- *Development Hardware:* Since Mac supports development for both android and IOS development, it would be the ideal choice of hardware for development purposes. This will help us stay away from working with virtual machines and make development easier.

- *IDE Choice*: For the android application we will develop in Android Studio, and for the IOS application we will develop in XCode.

- *Data-Security:* As mentioned in P.2, we are utilizing AWS as our cloud service provider. One of the security services we will use for data encryption is the Amazon S3 Buckets with service-side encryption.